# 🚀 Ściągawka z Machine Learningu dla Odkrywców!

Hej! Zgubiłeś się w gąszczu kodu? Nie pamiętasz, jak przefiltrować tabelę albo policzyć średnią? Bez stresu! Ta ściąga to Twój ratunek. Zebraliśmy tu wszystkie najważniejsze zaklęcia (czyli funkcje) z naszych warsztatów, podzielone na malutkie, łatwe do skopiowania kawałki.

## 🐍 Python

Zanim odpalimy sztuczną inteligencję, przypomnijmy sobie fundamenty.

### Zmienne (Twoje pudełka na dane)

Wyobraź sobie, że tworzysz postać w grze. Musisz gdzieś zapisać jej statystyki.

In [ ]:
hp = 100              # Liczba całkowita (int)
nick = "67dragon"     # Tekst (string) - zawsze w cudzysłowie!
czy_ma_tarcze = True  # Prawda/Fałsz (boolean)

### Listy (Twój ekwipunek)

Gdy chcesz trzymać wiele rzeczy w jednym miejscu. Pamiętaj: w programowaniu liczymy od zera!

In [ ]:
ekwipunek = ["Miecz", "Łuk", "Mikstura", "Złoto", "Mapa"]

### Wyciąganie rzeczy z listy

Wyciągamy pierwszy i ostatni przedmiot:

In [ ]:
pierwszy_item = ekwipunek[0]   # "Miecz"
ostatni_item = ekwipunek[-1]   # "Mapa" (minus jeden to zawsze koniec, a -2 to drugi od końca)

### Slicing (Wycinanie kawałków listy)

Co jeśli chcesz wyciągnąć np. 3 pierwsze przedmioty naraz? Używamy magicznego dwukropka `:`. Działa to jak zaznaczanie tekstu myszką.

In [ ]:
# Od indeksu 0 do 3 (ale BEZ trójki! Czyli weźmie 0, 1 i 2)
poczatek = ekwipunek[0:3]      # ["Miecz", "Łuk", "Mikstura"]
print("Początek", poczatek)

# Jeśli zaczynamy od zera, możemy je pominąć
szybki_poczatek = ekwipunek[:3]
print(f"Jak widać pierwsza opcja - [0:3] ({poczatek}) i druga opcja - [:3] ({szybki_poczatek}), są takie same!")

# Od indeksu 2 aż do samego końca (pamiętamy że liczymy od 0)
koncowka = ekwipunek[2:]
print("Koncówka", koncowka)

Początek ['Miecz', 'Łuk', 'Mikstura']
Jak widać pierwsza opcja - [0:3] (['Miecz', 'Łuk', 'Mikstura']) i druga opcja - [:3] (['Miecz', 'Łuk', 'Mikstura']), są takie same!
Koncówka ['Mikstura', 'Złoto', 'Mapa']

### Magiczny trik ze Slicingiem (Odwracanie)

Chcesz przeczytać listę od tyłu? Wystarczy użyć dwóch dwukropków i minus jedynki.

In [ ]:
odwrocony_ekwipunek = ekwipunek[::-1]
print(f"Normalny ekwipunek={ekwipunek}")
print(f"Odwrócony ekwipunek={odwrocony_ekwipunek}")

Normalny ekwipunek=['Miecz', 'Łuk', 'Mikstura', 'Złoto', 'Mapa']
Odwrócony ekwipunek=['Mapa', 'Złoto', 'Mikstura', 'Łuk', 'Miecz']

### Słowniki (Pokedex / Książka adresowa)

Przechowują dane w parach "Klucz: Wartość". Super przydatne, gdy chcesz coś szybko znaleźć po nazwie.

In [ ]:
statystyki = {
    "sila": 15,
    "zwinnosc": 10,
    "inteligencja": 5
}

### Jak czytać ze słownika?

Podajesz klucz w nawiasie kwadratowym i dostajesz wartość.

In [ ]:
punkty_sily = statystyki["sila"]
print(punkty_sily)  # Wypisze 15

15

### Instrukcje warunkowe If/Else

Logika gry. Zrób coś TYLKO jeśli warunek jest spełniony.

In [ ]:
if hp <= 0:    # jeśli straciłeś całe życie - umierasz
    print("Game Over! ☠️☠️☠️")
elif hp < 20:  # jeśli masz hp > 0, ale mniejsze niż 20 to wykonujemy kod poniżej
    print("Uwaga, mało życia! ⚠️")
else:          # jak żaden warunek nie jest spełniony wykonaj kod poniżej
    print("Walcz dalej! ⚔️")

Walcz dalej! ⚔️

### Pętla FOR

Nie chce Ci się pisać tego samego 100 razy? Użyj pętli. Kod wewnątrz wykona się dla każdego elementu z listy.

In [ ]:
for przedmiot in ekwipunek:
    print(f"Znalazłeś: {przedmiot}")

Znalazłeś: Miecz
Znalazłeś: Łuk
Znalazłeś: Mikstura
Znalazłeś: Złoto
Znalazłeś: Mapa

### Pętla FOR z licznikiem

Moglibyśmy chcieć zrobić `id` dla każdego przedmiotu.

Pamiętasz - `ekwipunek[i]` to element z listy ekwipunek o numerze i (czyli na początku 0, potem 1, potem 2. Jakbyśmy mięli dłuższą listę to 3, 4, 5...)

In [ ]:
for i in range(len(ekwipunek)):
  print(f"Przedmiot o id={i} nazywa się: {ekwipunek[i]}")

Przedmiot o id=0 nazywa się: Miecz
Przedmiot o id=1 nazywa się: Łuk
Przedmiot o id=2 nazywa się: Mikstura
Przedmiot o id=3 nazywa się: Złoto
Przedmiot o id=4 nazywa się: Mapa

### Funkcje (Tworzenie własnych zaklęć)

Zamykasz kawałek kodu w paczkę, nadajesz jej nazwę i wywołujesz kiedy tylko chcesz.

In [ ]:
def lecz_postac(aktualne_hp, mikstura_leczenia):
    nowe_hp = aktualne_hp + mikstura_leczenia
    return nowe_hp

### Używanie własnej funkcji

Żeby użyć funkcji musimy włożyć do niej argumenty, robimy to za pomocą okrągłych nawiasów. Poniżej do funkcji `lecz_postac` podajemy argumenty `aktualne_hp` i `mikstura_leczenia`, gdzie jako `aktualne_hp` przyjmiemy wartość zmiennej `hp` (czyli 100), a jako `mikstura_leczenia` (o ile uleczymy naszego bohatera) przyjmiemy 50 (bo tyle podaliśmy).

In [ ]:
hp = lecz_postac(hp, 50)
print(f"Moje aktualne hp: {hp}")

Moje aktualne hp: 150


## Numpy - Szybka matematyka

Zwykłe listy w Pythonie są fajne, ale wyobraź sobie, że musisz policzyć średnią ze 100 tysięcy ocen z całej Polski. Zwykły Python by się spocił i zawiesił. Numpy to takie matematyczne Ferrari - robi obliczenia na ogromnych zbiorach danych w ułamku sekundy!


### Jak zaimportować?

Zawsze robimy `as np` tylko dlatego żeby potem nie pisać za każdym razem `numpy`.

In [ ]:
import numpy as np

### Tworzenie "Array" (super-tablicy)

Array to podstawowy klocek, z którego budujemy nasze dane do AI. Wygląda trochę jak lista, którą już poznaliśmy wcześniej!

In [ ]:
zwykla_lista = [1, 2, 3, 4, 5]
super_tablica = np.array(zwykla_lista)
print(super_tablica)

[1 2 3 4 5]

### Średnia

Wyobraź sobie, że to czasy przejścia poziomu w grze. Ile średnio zajmuje ten poziom?

In [ ]:
czasy_w_grze = np.array([12, 15, 10, 20, 11])
srednia = np.mean(czasy_w_grze)
print(srednia)

13.6

### Mediana

Wartość "środkowa". Lepsza niż średnia, gdy np. jeden gracz poszedł na obiad w trakcie gry i zawyżył wynik.

In [ ]:
czasy_w_grze = np.array([12, 15, 10, 200, 11]) # Ten z 200 to ten od obiadu!
mediana = np.median(czasy_w_grze)
print(mediana)

12.0

### Wartość minimalna i maksymalna

Kto był najszybszy, a kto najwolniejszy?

In [ ]:
czasy_w_grze = np.array([12, 15, 10, 20, 11])
najszybszy = np.min(czasy_w_grze)
najwolniejszy = np.max(czasy_w_grze)
print("najszybszy:", najszybszy)
print("najwolniejszy:", najwolniejszy)

najszybszy: 10
najwolniejszy: 20

## 🐼 Pandas - Twój osobisty Excel w kodzie

To takie potężne narzędzie, w którym zamiast klikać myszką, piszesz krótkie komendy, żeby pracować na ogromnych tabelach.

### Jak zaimportować?

In [24]:
import pandas as pd

### Crafting własnej tabeli od zera (ze słownika)

Czasem nie masz pliku CSV, a po prostu chcesz wpisać dane ręcznie, np. statystyki swojej ekipy w grze. Klucze ze słownika to nazwy kolumn, a listy to ich zawartość!

In [57]:
dane = {
    "Nick": ["67dragon", "NoobMaster", "ProGamer", "Stockfish", "NullGamer"],
    "Level": [99, 5, 150, 99, None],
    "Ranga": ["Diament", "Brąz", "Challenger", "Diament", None]
}
df_wlasne = pd.DataFrame(dane)

### Zapisanie danych do pliku

Tworzymy zapis gry.

In [58]:
df_wlasne.to_csv('statystyki_gier.csv')

### Wczytywanie danych z pliku

Odpalanie naszego zapisu gry, który wkładamy do zmiennej df (od DataFrame).

In [59]:
df = pd.read_csv('statystyki_gier.csv')

### Szybki podgląd tabeli (head)

Pokazuje pierwsze wiersze. Domyślnie 5, ale jeśli wpiszesz w nawiasie np. 2, pokaże tylko dwa wiersze!

In [60]:
df.head(2)

   Unnamed: 0        Nick  Level    Ranga
0           0    67dragon   99.0  Diament
1           1  NoobMaster    5.0     Brąz

### Informacje o tabeli (info)

Ile jest wierszy? Jakie mamy kolumny? Czy czegoś nie brakuje?

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5 non-null      int64
 1   Nick        5 non-null      object
 2   Level       4 non-null      float64
 3   Ranga       4 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

### Podsumowanie matematyczne (describe)

Zwraca średnią, min, max i kwartyle dla KAŻDEJ liczbowej kolumny naraz! Magia.

In [62]:
df.describe()

       Unnamed: 0       Level
count    5.000000    4.000000
mean     2.000000   88.250000
std      1.581139   60.483469
min      0.000000    5.000000
25%      1.000000   75.500000
50%      2.000000   99.000000
75%      3.000000  111.750000
max      4.000000  150.000000

### Wyciąganie jednej kolumny

Jak z dużej tabeli wyciągnąć np. tylko same rangi?

In [63]:
rangi = df[['Ranga']]
rangi

        Ranga
0     Diament
1        Brąz
2  Challenger
3     Diament
4         NaN

### Sprawdzanie unikalnych wartości i topka

Jakie w ogóle mamy rangi (unique) i ile ich jest (value_counts)?

In [64]:
gatunki = df['Ranga'].unique()


print(gatunki)
df['Ranga'].value_counts()

['Diament' 'Brąz' 'Challenger' nan]

Ranga
Diament       2
Brąz          1
Challenger    1
Name: count, dtype: int64

### Filtrowanie (Jeden warunek)

Zostawiamy w tabeli tylko tych graczy, którzy są prawdziwymi prosami. (Pamiętamy o nawiasach kwadratowych []!)

In [65]:
pros = df[df['Level'] > 100]
pros

   Unnamed: 0      Nick  Level       Ranga
2           2  ProGamer  150.0  Challenger

### Filtrowanie z KILKOMA warunkami

Możemy teraz zobaczyć ile graczy, które nie są pro mają diamentową rangę!

MEGA WAŻNE: Używamy `&` (zamiast `and`) oraz `|` (zamiast `or`). ZAWSZE bierzemy każdy warunek w okrągłe nawiasy ()!

In [66]:
great_players = df[(df['Level'] < 100) & (df['Ranga'] == "Diament")]
great_players

   Unnamed: 0       Nick  Level    Ranga
0           0   67dragon   99.0  Diament
3           3  Stockfish   99.0  Diament

### Sprawdzanie braków danych (NaN)

Czasami w danych są dziury. Zobaczmy, gdzie nam czegoś brakuje:

In [67]:
print(df.isna().sum())

Unnamed: 0    0
Nick          0
Level         1
Ranga         1
dtype: int64

### Naprawa braków (Wyrzucanie i Wypełnianie)

Maszyny nienawidzą pustych dziur. Możesz usunąć puste wiersze albo wpisać tam domyślną wartość (np. 18).

In [70]:
czyste_dane = df.dropna()   # Brutalne wyrzucenie
dane_zalatane = df.fillna(18) # Podstawienie wartości

print("Zwykłe dane:")
print(df)
print("-" * 20)
print("Czyszczenie:")
print(czyste_dane)
print("-" * 20)
print("Zalatowanie:")
print(dane_zalatane)

Zwykłe dane:
   Unnamed: 0        Nick  Level       Ranga
0           0    67dragon   99.0     Diament
1           1  NoobMaster    5.0        Brąz
2           2    ProGamer  150.0  Challenger
3           3   Stockfish   99.0     Diament
4           4   NullGamer    NaN         NaN
--------------------
Czyszczenie:
   Unnamed: 0        Nick  Level       Ranga
0           0    67dragon   99.0     Diament
1           1  NoobMaster    5.0        Brąz
2           2    ProGamer  150.0  Challenger
3           3   Stockfish   99.0     Diament
--------------------
Zalatowanie:
   Unnamed: 0        Nick  Level       Ranga
0           0    67dragon   99.0     Diament
1           1  NoobMaster    5.0        Brąz
2           2    ProGamer  150.0  Challenger
3           3   Stockfish   99.0     Diament
4           4   NullGamer   18.0          18

## 🤖 Scikit-Learn (sklearn) - Fabryka Sztucznej Inteligencji

W `scikit-learn` znajdują się wszystkie popularne modele uczenia maszynowego.

Pamiętaj: schemat działania to ZAWSZE: Wybierz model -> Naucz go (.fit) -> Zgaduj (.predict).

### Import i przygotowanie danych

Duże X to cechy (np. wiek i waga), a małe y to etykiety (np. 0=Kot, 1=Pies).

In [71]:
from sklearn.neighbors import KNeighborsClassifier

X = np.array([[1, 2], [2, 3], [8, 9], [9, 10]])
y = np.array([0, 0, 1, 1])

### Wybierz i skonfiguruj model

Wybieramy naszą broń. Tutaj algorytm KNN (pytamy 3 najbliższych sąsiadów).

In [72]:
model = KNeighborsClassifier(n_neighbors=3)

### Trenowanie modelu (FIT)

Magia! Tutaj model się uczy. Odkrywa zależności między cechami (X) a odpowiedziami (y).

In [73]:
model.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

### Przewidywanie (PREDICT)

Przyszedł nowy, nieznany zwierzak. Zgadnij, co to jest!

In [75]:
nowy_zwierzak = np.array([[7, 8]])
przewidywanie = model.predict(nowy_zwierzak)
print(przewidywanie)

[1]

### Ocenianie modelu (SCORE)

Wrzucamy mu testowe dane (kartkówkę) i patrzymy, jak dobrze sobie poradził (wynik od 0.0 do 1.0).

In [82]:
X_test = np.array([[1, 2], [5, 9], [0,2]])
y_test = np.array([0, 1, 0])

dokladnosc = model.score(X_test, y_test)
dokladnosc

1.0